export const moviesData = [
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3525/35254795_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "The Father",
        date: "Decembre 2021",
        desc: "THE FATHER raconte la trajectoire intérieure d’un homme de 81 ans, Anthony, dont la réalité se brise peu à peu sous nos yeux. Mais c’est aussi l’histoire d’Anne, sa fille, qui tente de l’accompagner dans un labyrinthe de questions sans réponses",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3522/35220581_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 3,
        name: "The Marksman",
        date: "Decembre 2021",
        desc: "Release Date:05/11/2021",
    },  
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6469/6469286_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 5,
        name: "The Fast Saga",
        date: "Decembre 2021",
        desc: "The Fast And Fersous",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8773/8773534_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "Indiana Jones Doom",
        date: "05/13/2008",
        desc: "Special Edition] [DVD] [1984]",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6282/6282124_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "Breaking In",
        date: "08/07/2018",
        desc: "Breaking In: Directed by James McTeigue",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3500/35003697_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 3,
        name: "Last Shot",
        date: "08/25/2020",
        desc: "Last Shot: Directed by Terrence Arlyn. With Terrence Arlyn",
    },
    
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3525/35254795_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "The Father",
        date: "Decembre 2021",
        desc: "THE FATHER raconte la trajectoire intérieure d’un homme de 81 ans, Anthony, dont la réalité se brise peu à peu sous nos yeux. Mais c’est aussi l’histoire d’Anne, sa fille, qui tente de l’accompagner dans un labyrinthe de questions sans réponses",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3522/35220581_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 3,
        name: "The Marksman",
        date: "Decembre 2021",
        desc: "Release Date:05/11/2021",
    },  
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6469/6469286_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 5,
        name: "The Fast Saga",
        date: "Decembre 2021",
        desc: "The Fast And Fersous",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/8773/8773534_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "Indiana Jones Doom",
        date: "05/13/2008",
        desc: "Special Edition] [DVD] [1984]",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6282/6282124_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 4,
        name: "Breaking In",
        date: "08/07/2018",
        desc: "Breaking In: Directed by James McTeigue",
    },
    {
        id:Math.random(),
        image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/3500/35003697_sa.jpg;maxHeight=640;maxWidth=550",
        rating: 3,
        name: "Last Shot",
        date: "08/25/2020",
        desc: "Last Shot: Directed by Terrence Arlyn. With Terrence Arlyn",
    },
]